services:
  app:
    image: registry.digitalocean.com/devops-kurs-registry/my-node-app:1.0.1
#    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - app_data:/opt/app/storage
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    deploy:
      replicas: 10
      update_config:
        parallelism: 3
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: curl -sS http://127.0.0.1:3000 || echo 1
      interval: 30s
      timeout: 3s
      retries: 12
#  db:
#    image: postgres:15.13-alpine3.21
#    ports:
#      - "5432:5432"
#    restart: unless-stopped
#    environment:
#      POSTGRES_PASSWORD: "mysecretpassword"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#  redis:
#    image: redis:7.2.8-alpine3.21
##    ports:
##      - "6379:6379"
#    restart: unless-stopped

volumes:
  pgdata:
  app_data: